language: "java"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - .autoconf
    - $HOME/.m2
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "/home/travis/build/manami-project/manami/gui/target/manami.jar"
  skip_cleanup: true
  on:
    tags: true