language: "java"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
after_success:
  - bash <(curl -s https://codecov.io/bash)